In [1]:
import numpy as np



In [9]:
#Create an array
arr = np.arange(5)

In [10]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)

In [11]:
#Change arr
arr = np.arange(10)
#Show
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Lets see the original saved copy
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [13]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr)

In [14]:
#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')

#Show
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Now lets remove them from the memory
rm my_array.npy
rm two_arrays.npz

SyntaxError: invalid syntax (<ipython-input-8-7d53e496e836>, line 2)

In [15]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [16]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])