In [1]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Taking Square Roots
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
#Calcualting exponential (e^)
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([-0.93392052,  1.16679423, -1.02262162, -0.56667618, -0.64507824,
        1.03478296,  0.25589871, -0.4987126 ,  1.22405392, -0.11176354])

In [6]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([ 0.09540002,  1.61776086,  1.43684158, -0.03873328, -0.04863653,
       -0.5701209 ,  0.76942087,  0.51813419,  0.39362434,  1.16736285])

In [7]:
#Addition
np.add(A,B)

array([-0.8385205 ,  2.78455509,  0.41421997, -0.60540945, -0.69371477,
        0.46466207,  1.02531959,  0.01942159,  1.61767826,  1.05559931])

In [9]:
#Finding max or min between two arrays
np.maximum(A,B)

array([ 0.09540002,  1.61776086,  1.43684158, -0.03873328, -0.04863653,
        1.03478296,  0.76942087,  0.51813419,  1.22405392,  1.16736285])

In [10]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True